// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/indexer/block/v1/avg_blocktime": {
            "get": {
                "description": "Get the average block time over recent blocks",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Block"
                ],
                "summary": "Get average block time",
                "responses": {}
            }
        },
        "/indexer/block/v1/blocks": {
            "get": {
                "description": "Get a list of blocks with pagination",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Block"
                ],
                "summary": "Get blocks",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Pagination key",
                        "name": "pagination.key",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Pagination offset",
                        "name": "pagination.offset",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Pagination limit, default is 100",
                        "name": "pagination.limit",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "Reverse order, default is true. if set to true, the results will be ordered in descending order",
                        "name": "pagination.reverse",
                        "in": "query"
                    }
                ],
                "responses": {}
            }
        },
        "/indexer/block/v1/blocks/{height}": {
            "get": {
                "description": "Get a specific block by its height",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Block"
                ],
                "summary": "Get block by height",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Block height",
                        "name": "height",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/indexer/nft/v1/collections": {
            "get": {
                "description": "Get NFT collections",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "NFT"
                ],
                "summary": "Get NFT collections",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Pagination key",
                        "name": "pagination.key",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Pagination offset",
                        "name": "pagination.offset",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Pagination limit, default is 100",
                        "name": "pagination.limit",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "Count total, default is true",
                        "name": "pagination.count_total",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "Reverse order default is true if set to true, the results will be ordered in descending order",
                        "name": "pagination.reverse",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/nft.CollectionsResponse"
                        }
                    }
                }
            }
        },
        "/indexer/nft/v1/collections/by_account/{account}": {
            "get": {
                "description": "Get NFT collections owned by a specific account",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "NFT"
                ],
                "summary": "Get NFT collections by account",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Account address",
                        "name": "account",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Pagination key",
                        "name": "pagination.key",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Pagination offset",
                        "name": "pagination.offset",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Pagination limit, default is 100",
                        "name": "pagination.limit",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "Count total, default is true",
                        "name": "pagination.count_total",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "Reverse order default is true if set to true, the results will be ordered in descending order",
                        "name": "pagination.reverse",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/nft.CollectionsResponse"
                        }
                    }
                }
            }
        },
        "/indexer/nft/v1/collections/by_name/{name}": {
            "get": {
                "description": "Get NFT collections for a specific name",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "NFT"
                ],
                "summary": "Get NFT collections by name",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Collection name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Pagination key",
                        "name": "pagination.key",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Pagination offset",
                        "name": "pagination.offset",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Pagination limit, default is 100",
                        "name": "pagination.limit",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "Count total, default is true",
                        "name": "pagination.count_total",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "Reverse order default is true if set to true, the results will be ordered in descending order",
                        "name": "pagination.reverse",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/nft.CollectionsResponse"
                        }
                    }
                }
            }
        },
        "/indexer/nft/v1/collections/{collection_addr}": {
            "get": {
                "description": "Get NFT collections for a specific address",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "NFT"
                ],
                "summary": "Get NFT Collections By Collection Address",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Collection address",
                        "name": "collection_addr",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/nft.CollectionResponse"
                        }
                    }
                }
            }
        },
        "/indexer/nft/v1/tokens/by_account/{account}": {
            "get": {
                "description": "Get NFT tokens owned by a specific account",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "NFT"
                ],
                "summary": "Get NFT tokens by account",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Account address",
                        "name": "account",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Collection address to filter by (optional)",
                        "name": "collection_addr",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Token ID to filter by (optional)",
                        "name": "token_id",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "token_id",
                            "height"
                        ],
                        "type": "string",
                        "default": "token_id",
                        "description": "Order by field",
                        "name": "order_by",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Pagination key",
                        "name": "pagination.key",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Pagination offset",
                        "name": "pagination.offset",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Pagination limit, default is 100",
                        "name": "pagination.limit",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "Count total, default is true",
                        "name": "pagination.count_total",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "Reverse order default is true if set to true, the results will be ordered in descending order",
                        "name": "pagination.reverse",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/nft.NftsResponse"
                        }
                    }
                }
            }
        },
        "/indexer/nft/v1/tokens/by_collection/{collection_addr}": {
            "get": {
                "description": "Get NFT tokens from a specific collection",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "NFT"
                ],
                "summary": "Get NFT tokens by collection",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Collection address",
                        "name": "collection_addr",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Token ID to filter by (optional)",
                        "name": "token_id",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "token_id",
                            "height"
                        ],
                        "type": "string",
                        "default": "token_id",
                        "description": "Order by field",
                        "name": "order_by",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Pagination key",
                        "name": "pagination.key",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Pagination offset",
                        "name": "pagination.offset",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Pagination limit, default is 100",
                        "name": "pagination.limit",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "Count total, default is true",
                        "name": "pagination.count_total",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "Reverse order default is true if set to true, the results will be ordered in descending order",
                        "name": "pagination.reverse",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/nft.NftsResponse"
                        }
                    }
                }
            }
        },
        "/indexer/nft/v1/txs/{collection_addr}/{token_id}": {
            "get": {
                "description": "Get NFT transactions for a specific collection and token ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "NFT"
                ],
                "summary": "Get NFT transactions by collection and token ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Collection address",
                        "name": "collection_addr",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Token ID",
                        "name": "token_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Pagination key",
                        "name": "pagination.key",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Pagination offset",
                        "name": "pagination.offset",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Pagination limit, default is 100",
                        "name": "pagination.limit",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "Count total, default is true",
                        "name": "pagination.count_total",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "Reverse order default is true if set to true, the results will be ordered in descending order",
                        "name": "pagination.reverse",
                        "in": "query"
                    }
                ],
                "responses": {}
            }
        },
        "/indexer/tx/v1/evm-internal-txs": {
            "get": {
                "description": "Get a list of EVM internal transactions with pagination",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "EVM Internal Tx"
                ],
                "summary": "Get EVM internal transactions",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Pagination key",
                        "name": "pagination.key",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Pagination offset",
                        "name": "pagination.offset",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Pagination limit, default is 100",
                        "name": "pagination.limit",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "Count total, default is true",
                        "name": "pagination.count_total",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "Reverse order default is true if set to true, the results will be ordered in descending order",
                        "name": "pagination.reverse",
                        "in": "query"
                    }
                ],
                "responses": {}
            }
        },
        "/indexer/tx/v1/evm-internal-txs/by_account/{account}": {
            "get": {
                "description": "Get EVM internal transactions associated with a specific account",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "EVM Internal Tx"
                ],
                "summary": "Get EVM internal transactions by account",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Account address",
                        "name": "account",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Pagination key",
                        "name": "pagination.key",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Pagination offset",
                        "name": "pagination.offset",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Pagination limit, default is 100",
                        "name": "pagination.limit",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "Count total, default is true",
                        "name": "pagination.count_total",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "Reverse order default is true if set to true, the results will be ordered in descending order",
                        "name": "pagination.reverse",
                        "in": "query"
                    }
                ],
                "responses": {}
            }
        },
        "/indexer/tx/v1/evm-internal-txs/by_height/{height}": {
            "get": {
                "description": "Get EVM internal transactions at a specific block height",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "EVM Internal Tx"
                ],
                "summary": "Get EVM internal transactions by height",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Block height",
                        "name": "height",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Pagination key",
                        "name": "pagination.key",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Pagination offset",
                        "name": "pagination.offset",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Pagination limit, default is 100",
                        "name": "pagination.limit",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "Count total, default is true",
                        "name": "pagination.count_total",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "Reverse order default is true if set to true, the results will be ordered in descending order",
                        "name": "pagination.reverse",
                        "in": "query"
                    }
                ],
                "responses": {}
            }
        },
        "/indexer/tx/v1/evm-internal-txs/{tx_hash}": {
            "get": {
                "description": "Get a specific EVM internal transaction by its hash",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "EVM Internal Tx"
                ],
                "summary": "Get EVM internal transaction by hash",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Transaction hash",
                        "name": "tx_hash",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Pagination key",
                        "name": "pagination.key",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Pagination offset",
                        "name": "pagination.offset",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Pagination limit, default is 100",
                        "name": "pagination.limit",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "Count total, default is true",
                        "name": "pagination.count_total",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "Reverse order default is true if set to true, the results will be ordered in descending order",
                        "name": "pagination.reverse",
                        "in": "query"
                    }
                ],
                "responses": {}
            }
        },
        "/indexer/tx/v1/evm-txs": {
            "get": {
                "description": "Get a list of EVM transactions with pagination",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "EVM Tx"
                ],
                "summary": "Get EVM transactions",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Pagination key",
                        "name": "pagination.key",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Pagination offset",
                        "name": "pagination.offset",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Pagination limit, default is 100",
                        "name": "pagination.limit",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "Count total, default is true",
                        "name": "pagination.count_total",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "Reverse order default is true if set to true, the results will be ordered in descending order",
                        "name": "pagination.reverse",
                        "in": "query"
                    }
                ],
                "responses": {}
            }
        },
        "/indexer/tx/v1/evm-txs/by_account/{account}": {
            "get": {
                "description": "Get EVM transactions associated with a specific account",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "EVM Tx"
                ],
                "summary": "Get EVM transactions by account",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Account address",
                        "name": "account",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Pagination key",
                        "name": "pagination.key",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Pagination offset",
                        "name": "pagination.offset",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Pagination limit, default is 100",
                        "name": "pagination.limit",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "Count total, default is true",
                        "name": "pagination.count_total",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "Reverse order default is true if set to true, the results will be ordered in descending order",
                        "name": "pagination.reverse",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "Filter by signer accounts, default is false",
                        "name": "is_signer",
                        "in": "query"
                    }
                ],
                "responses": {}
            }
        },
        "/indexer/tx/v1/evm-txs/by_height/{height}": {
            "get": {
                "description": "Get EVM transactions at a specific block height",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "EVM Tx"
                ],
                "summary": "Get EVM transactions by height",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Block height",
                        "name": "height",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Pagination key",
                        "name": "pagination.key",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Pagination offset",
                        "name": "pagination.offset",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Pagination limit, default is 100",
                        "name": "pagination.limit",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "Count total, default is true",
                        "name": "pagination.count_total",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "Reverse order default is true if set to true, the results will be ordered in descending order",
                        "name": "pagination.reverse",
                        "in": "query"
                    }
                ],
                "responses": {}
            }
        },
        "/indexer/tx/v1/evm-txs/{tx_hash}": {
            "get": {
                "description": "Get a specific EVM transaction by its hash",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "EVM Tx"
                ],
                "summary": "Get EVM transaction by hash",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Transaction hash",
                        "name": "tx_hash",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/indexer/tx/v1/txs": {
            "get": {
                "description": "Get a list of transactions with pagination",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Tx"
                ],
                "summary": "Get transactions",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Pagination key",
                        "name": "pagination.key",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Pagination offset",
                        "name": "pagination.offset",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Pagination limit, default is 100",
                        "name": "pagination.limit",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "Count total, default is true",
                        "name": "pagination.count_total",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "Reverse order default is true if set to true, the results will be ordered in descending order",
                        "name": "pagination.reverse",
                        "in": "query"
                    },
                    {
                        "type": "array",
                        "items": {
                            "type": "string"
                        },
                        "collectionFormat": "multi",
                        "example": "\"cosmos.bank.v1beta1.MsgSend,initia.move.v1.MsgExecute\"",
                        "description": "Message types to filter (comma-separated or multiple params)",
                        "name": "msgs",
                        "in": "query"
                    }
                ],
                "responses": {}
            }
        },
        "/indexer/tx/v1/txs/by_account/{account}": {
            "get": {
                "description": "Get transactions associated with a specific account",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Tx"
                ],
                "summary": "Get transactions by account",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Account address",
                        "name": "account",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Pagination key",
                        "name": "pagination.key",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Pagination offset",
                        "name": "pagination.offset",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Pagination limit, default is 100",
                        "name": "pagination.limit",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "Count total, default is true",
                        "name": "pagination.count_total",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "Reverse order default is true if set to true, the results will be ordered in descending order",
                        "name": "pagination.reverse",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "Filter by signer accounts, default is false",
                        "name": "is_signer",
                        "in": "query"
                    },
                    {
                        "type": "array",
                        "items": {
                            "type": "string"
                        },
                        "collectionFormat": "multi",
                        "example": "\"cosmos.bank.v1beta1.MsgSend,initia.move.v1.MsgExecute\"",
                        "description": "Message types to filter (comma-separated or multiple params)",
                        "name": "msgs",
                        "in": "query"
                    }
                ],
                "responses": {}
            }
        },
        "/indexer/tx/v1/txs/by_height/{height}": {
            "get": {
                "description": "Get transactions at a specific block height",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Tx"
                ],
                "summary": "Get transactions by height",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Block height",
                        "name": "height",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Pagination key",
                        "name": "pagination.key",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Pagination offset",
                        "name": "pagination.offset",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Pagination limit, default is 100",
                        "name": "pagination.limit",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "Count total, default is true",
                        "name": "pagination.count_total",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "Reverse order default is true if set to true, the results will be ordered in descending order",
                        "name": "pagination.reverse",
                        "in": "query"
                    },
                    {
                        "type": "array",
                        "items": {
                            "type": "string"
                        },
                        "collectionFormat": "multi",
                        "example": "\"cosmos.bank.v1beta1.MsgSend,initia.move.v1.MsgExecute\"",
                        "description": "Message types to filter (comma-separated or multiple params)",
                        "name": "msgs",
                        "in": "query"
                    }
                ],
                "responses": {}
            }
        },
        "/indexer/tx/v1/txs/{tx_hash}": {
            "get": {
                "description": "Get a specific transaction by its hash",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Tx"
                ],
                "summary": "Get transaction by hash",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Transaction hash",
                        "name": "tx_hash",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/richlist/v1/{denom}": {
            "get": {
                "description": "Get a list of token holders for a specific denomination, ordered by amount in descending order",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Rich List"
                ],
                "summary": "Get token holders",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Token denomination",
                        "name": "denom",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Pagination key",
                        "name": "pagination.key",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Pagination offset",
                        "name": "pagination.offset",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Pagination limit, default is 100",
                        "name": "pagination.limit",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "Count total, default is true",
                        "name": "pagination.count_total",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "Reverse order default is true if set to true, the results will be ordered in descending order",
                        "name": "pagination.reverse",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/richlist.TokenHoldersResponse"
                        }
                    }
                }
            }
        },
        "/status": {
            "get": {
                "description": "Get current indexer status including chain ID and latest block height",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "App"
                ],
                "summary": "Status check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/status.StatusResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "common.PaginationResponse": {
            "type": "object",
            "properties": {
                "next_key": {
                    "type": "string",
                    "x-order:1": true
                },
                "previous_key": {
                    "type": "string",
                    "x-order:0": true
                },
                "total": {
                    "type": "string",
                    "x-order:2": true
                }
            }
        },
        "nft.Collection": {
            "type": "object",
            "properties": {
                "collection": {
                    "allOf": [
                        {
                            "$ref": "#/definitions/nft.CollectionDetail"
                        }
                    ],
                    "x-order:1": true
                },
                "height": {
                    "type": "integer",
                    "x-order:2": true
                },
                "object_addr": {
                    "type": "string",
                    "x-order:0": true
                },
                "timestamp": {
                    "type": "string",
                    "x-order:3": true
                }
            }
        },
        "nft.CollectionDetail": {
            "type": "object",
            "properties": {
                "creator": {
                    "type": "string",
                    "x-order:0": true
                },
                "name": {
                    "type": "string",
                    "x-order:1": true
                },
                "nfts": {
                    "allOf": [
                        {
                            "$ref": "#/definitions/nft.NftHandle"
                        }
                    ],
                    "x-order:4": true
                },
                "origin_name": {
                    "type": "string",
                    "x-order:2": true
                }
            }
        },
        "nft.CollectionResponse": {
            "type": "object",
            "properties": {
                "collection": {
                    "$ref": "#/definitions/nft.Collection"
                }
            }
        },
        "nft.CollectionsResponse": {
            "type": "object",
            "properties": {
                "collections": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/nft.Collection"
                    },
                    "x-order:0": true
                },
                "pagination": {
                    "allOf": [
                        {
                            "$ref": "#/definitions/common.PaginationResponse"
                        }
                    ],
                    "x-order:1": true
                }
            }
        },
        "nft.Nft": {
            "type": "object",
            "properties": {
                "collection_addr": {
                    "type": "string",
                    "x-order:0": true
                },
                "collection_name": {
                    "type": "string",
                    "x-order:1": true
                },
                "collection_origin_name": {
                    "type": "string",
                    "x-order:2": true
                },
                "height": {
                    "type": "integer",
                    "x-order:6": true
                },
                "nft": {
                    "allOf": [
                        {
                            "$ref": "#/definitions/nft.NftDetails"
                        }
                    ],
                    "x-order:5": true
                },
                "object_addr": {
                    "description": "only used in Move",
                    "type": "string",
                    "x-order:3": true
                },
                "owner": {
                    "type": "string",
                    "x-order:4": true
                },
                "timestamp": {
                    "type": "string",
                    "x-order:7": true
                }
            }
        },
        "nft.NftDetails": {
            "type": "object",
            "properties": {
                "token_id": {
                    "type": "string",
                    "x-order:2": true
                },
                "uri": {
                    "type": "string",
                    "x-order:3": true
                }
            }
        },
        "nft.NftHandle": {
            "type": "object",
            "properties": {
                "handle": {
                    "type": "string",
                    "x-order:0": true
                },
                "length": {
                    "type": "integer",
                    "x-order:1": true
                }
            }
        },
        "nft.NftsResponse": {
            "type": "object",
            "properties": {
                "pagination": {
                    "allOf": [
                        {
                            "$ref": "#/definitions/common.PaginationResponse"
                        }
                    ],
                    "x-order:1": true
                },
                "tokens": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/nft.Nft"
                    },
                    "x-order:0": true
                }
            }
        },
        "richlist.TokenHolder": {
            "type": "object",
            "properties": {
                "account": {
                    "type": "string"
                },
                "amount": {
                    "type": "string"
                }
            }
        },
        "richlist.TokenHoldersResponse": {
            "type": "object",
            "properties": {
                "holders": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/richlist.TokenHolder"
                    }
                },
                "pagination": {
                    "$ref": "#/definitions/common.PaginationResponse"
                }
            }
        },
        "status.StatusResponse": {
            "type": "object",
            "properties": {
                "chain_id": {
                    "type": "string",
                    "x-order:2": true
                },
                "commit_hash": {
                    "type": "string",
                    "x-order:1": true
                },
                "height": {
                    "type": "integer",
                    "x-order:3": true
                },
                "internal_tx_height": {
                    "type": "integer",
                    "x-order:4": true
                },
                "rich_list_height": {
                    "type": "integer",
                    "x-order:5": true
                },
                "version": {
                    "type": "string",
                    "x-order:0": true
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
