-- Create index "account_tx_account_hash" to table: "account_tx"
CREATE INDEX "account_tx_account_hash" ON "public"."account_tx" ("account", "hash");
-- Create index "block_height_desc" to table: "block"
CREATE INDEX "block_height_desc" ON "public"."block" ("height" DESC);
-- Create index "evm_account_tx_account_hash" to table: "evm_account_tx"
CREATE INDEX "evm_account_tx_account_hash" ON "public"."evm_account_tx" ("account", "hash");
-- Create index "evm_tx_sequence_desc" to table: "evm_tx"
CREATE INDEX "evm_tx_sequence_desc" ON "public"."evm_tx" ("sequence" DESC);
-- Create index "nft_collection_addr_token_id" to table: "nft"
CREATE INDEX "nft_collection_addr_token_id" ON "public"."nft" ("collection_addr", "token_id");
-- Create index "tx_sequence_desc" to table: "tx"
CREATE INDEX "tx_sequence_desc" ON "public"."tx" ("sequence" DESC);
